# -*- coding: utf-8 -*-
"""이메일 인증 코드.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmDTp-kCW9XfWmddq8jovIOnVwWOFCH-
"""

mail_add = input("학교 이메일 주소를 입력해 주세요.")

if "ajou.ac.kr" in mail_add:

    print("OK")

else:
    mail_add = 0
    print("Not allowed")


import random
random_key = str(random.randrange(100000, 999999))

import smtplib
from email.mime.text import MIMEText


smtp = smtplib.SMTP('smtp.gmail.com', 587)

smtp.ehlo()

smtp.starttls()

smtp.login('hexagono1434@gmail.com', 'orpgcusvllyjmpqw')

msg = MIMEText("인증을 위해 다음 6자리 숫자를 입력해 주세요. "+random_key)
msg['Subject'] = '폼페이 서비스 회원가입 test: 학교 Google Account 인증메일'

smtp.sendmail('hexagono1434@gmail.com', mail_add , msg.as_string())

smtp.quit()

verification_code = input("메일로 받은 6자리 숫자")

if verification_code == random_key:

    print("아주대 구성원 여러분 환영합니다.")

else:

    print("전송된 숫자와 일치하지 않습니다. 다시한번 확인해주십시오.")
